services:
  - type: web
    name: 21ktools
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn tools21k.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
