# Generated by Django 5.1.6 on 2025-10-02 09:17

import django.db.models.deletion
import qrscanner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='qr_uploads/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('decoded_text', models.TextField()),
                ('scan_id', models.CharField(db_index=True, default=qrscanner.models.generate_scan_id, max_length=20, unique=True)),
                ('secret_code', models.CharField(db_index=True, default=qrscanner.models.generate_secret_code, max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='qrscanner.qrcodescan')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
