# Generated by Django 5.1.6 on 2025-10-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='profile_picture_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='profile_picture_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='profile_picture_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
