# Generated by Django 5.1.6 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_set_site_domain"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN IF NOT EXISTS thumbnail_data bytea;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_data;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN IF NOT EXISTS thumbnail_name varchar(255) "
                "DEFAULT '';"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_name;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN IF NOT EXISTS thumbnail_type varchar(50) "
                "DEFAULT '';"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_type;"
            ),
        ),
    ]
