# Generated by Django 5.1.6 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_set_site_domain"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN IF NOT EXISTS thumbnail_data bytea;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_data;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN IF NOT EXISTS profile_picture_data bytea;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_data;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_blogpost' "
                "AND column_name = 'thumbnail_name'"
                ") THEN "
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN thumbnail_name varchar(255); "
                "END IF; "
                "UPDATE blog_blogpost "
                "SET thumbnail_name = '' "
                "WHERE thumbnail_name IS NULL; "
                "ALTER TABLE blog_blogpost "
                "ALTER COLUMN thumbnail_name SET DEFAULT ''; "
                "ALTER TABLE blog_blogpost "
                "ALTER COLUMN thumbnail_name SET NOT NULL; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_name;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_blogpost' "
                "AND column_name = 'thumbnail_type'"
                ") THEN "
                "ALTER TABLE blog_blogpost "
                "ADD COLUMN thumbnail_type varchar(50); "
                "END IF; "
                "UPDATE blog_blogpost "
                "SET thumbnail_type = '' "
                "WHERE thumbnail_type IS NULL; "
                "ALTER TABLE blog_blogpost "
                "ALTER COLUMN thumbnail_type SET DEFAULT ''; "
                "ALTER TABLE blog_blogpost "
                "ALTER COLUMN thumbnail_type SET NOT NULL; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_blogpost "
                "DROP COLUMN IF EXISTS thumbnail_type;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_authorprofile' "
                "AND column_name = 'profile_picture_name'"
                ") THEN "
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN profile_picture_name varchar(255); "
                "END IF; "
                "UPDATE blog_authorprofile "
                "SET profile_picture_name = '' "
                "WHERE profile_picture_name IS NULL; "
                "ALTER TABLE blog_authorprofile "
                "ALTER COLUMN profile_picture_name SET DEFAULT ''; "
                "ALTER TABLE blog_authorprofile "
                "ALTER COLUMN profile_picture_name SET NOT NULL; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_name;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_authorprofile' "
                "AND column_name = 'profile_picture_type'"
                ") THEN "
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN profile_picture_type varchar(50); "
                "END IF; "
                "UPDATE blog_authorprofile "
                "SET profile_picture_type = '' "
                "WHERE profile_picture_type IS NULL; "
                "ALTER TABLE blog_authorprofile "
                "ALTER COLUMN profile_picture_type SET DEFAULT ''; "
                "ALTER TABLE blog_authorprofile "
                "ALTER COLUMN profile_picture_type SET NOT NULL; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_type;"
            ),
        ),
    ]

