# Generated by Django 5.1.6 on 2026-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_fix_missing_thumbnail_columns"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN IF NOT EXISTS profile_picture_data bytea;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_data;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_authorprofile' "
                "AND column_name = 'profile_picture_name'"
                ") THEN "
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN profile_picture_name varchar(255); "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_name;"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "DO $$ "
                "BEGIN "
                "IF NOT EXISTS ("
                "SELECT 1 "
                "FROM information_schema.columns "
                "WHERE table_name = 'blog_authorprofile' "
                "AND column_name = 'profile_picture_type'"
                ") THEN "
                "ALTER TABLE blog_authorprofile "
                "ADD COLUMN profile_picture_type varchar(50); "
                "END IF; "
                "END $$;"
            ),
            reverse_sql=(
                "ALTER TABLE blog_authorprofile "
                "DROP COLUMN IF EXISTS profile_picture_type;"
            ),
        ),
    ]

