# Generated by Django 5.1.6 on 2026-01-27 18:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkQRBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_codes', models.IntegerField(default=0)),
                ('generated_codes', models.IntegerField(default=0)),
                ('design_template', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('retail', 'Retail & Shopping'), ('events', 'Events & Entertainment'), ('business', 'Business & Corporate'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real-estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('technology', 'Technology'), ('general', 'General Purpose')], max_length=30)),
                ('design_config', models.JSONField(default=dict, help_text='Complete design configuration')),
                ('preview_image', models.URLField(blank=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['industry', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('analytics_code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('qr_type', models.CharField(choices=[('url', 'Website URL'), ('vcard', 'Contact Card (vCard)'), ('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Number'), ('wifi', 'WiFi Network'), ('upi', 'UPI Payment'), ('location', 'Location/Address'), ('text', 'Plain Text'), ('whatsapp', 'WhatsApp'), ('profile', 'Profile Card')], default='url', max_length=20)),
                ('content_data', models.JSONField(default=dict, help_text='Structured data for QR content')),
                ('final_url', models.URLField(blank=True, help_text='Final generated URL/data', max_length=2000)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('gradient_enabled', models.BooleanField(default=False)),
                ('gradient_color', models.CharField(blank=True, max_length=7)),
                ('gradient_type', models.CharField(choices=[('linear', 'Linear'), ('radial', 'Radial')], default='linear', max_length=20)),
                ('frame_style', models.CharField(choices=[('none', 'No Frame'), ('square', 'Square Frame'), ('rounded', 'Rounded Frame'), ('circle', 'Circle Frame'), ('badge', 'Badge Frame'), ('scan-me', 'Scan Me Frame'), ('modern', 'Modern Frame'), ('vintage', 'Vintage Frame'), ('neon', 'Neon Frame'), ('minimal', 'Minimal Frame')], default='none', max_length=20)),
                ('pattern_style', models.CharField(choices=[('square', 'Square'), ('dots', 'Dots'), ('rounded', 'Rounded'), ('classy', 'Classy'), ('classy-rounded', 'Classy Rounded'), ('extra-rounded', 'Extra Rounded'), ('fluid', 'Fluid')], default='square', max_length=20)),
                ('eye_style', models.CharField(choices=[('square', 'Square'), ('circle', 'Circle'), ('rounded', 'Rounded'), ('leaf', 'Leaf'), ('flower', 'Flower')], default='square', max_length=20)),
                ('has_logo', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True)),
                ('logo_shape', models.CharField(choices=[('square', 'Square'), ('circle', 'Circle')], default='square', max_length=10)),
                ('logo_size', models.IntegerField(default=20, help_text='Logo size percentage')),
                ('size', models.IntegerField(default=300)),
                ('error_correction', models.CharField(choices=[('L', 'Low (7%)'), ('M', 'Medium (15%)'), ('Q', 'Quartile (25%)'), ('H', 'High (30%)')], default='M', max_length=1)),
                ('is_dynamic', models.BooleanField(default=True)),
                ('redirect_url', models.URLField(blank=True, help_text='Actual redirect URL for dynamic QR', max_length=2000)),
                ('qr_image', models.TextField(help_text='Base64 encoded QR image')),
                ('qr_image_url', models.URLField(blank=True, help_text='Cloudinary URL if uploaded')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('folder_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_scans', models.IntegerField(default=0)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analytics_code'], name='qrtools_qrc_analyti_351be0_idx'), models.Index(fields=['folder_name'], name='qrtools_qrc_folder__c9bb2a_idx'), models.Index(fields=['qr_type'], name='qrtools_qrc_qr_type_4c83fe_idx'), models.Index(fields=['-created_at'], name='qrtools_qrc_created_851a42_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('profile_photo', models.URLField(blank=True)),
                ('cover_photo', models.URLField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='[{label, value, icon}]')),
                ('theme_color', models.CharField(default='#667eea', max_length=7)),
                ('layout_style', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('professional', 'Professional'), ('gradient', 'Gradient')], default='modern', max_length=20)),
                ('page_views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_card', to='qrtools.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('browser', models.CharField(default='unknown', max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('region', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.CharField(default='0', max_length=20)),
                ('longitude', models.CharField(default='0', max_length=20)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='qrtools.qrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
