# Generated by Django 5.1.6 on 2026-01-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrtools', '0002_add_analytics_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='unique_id',
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['analytics_key'], name='qrtools_qrc_analyti_9dfb1c_idx'),
        ),
    ]
