"""
Django settings for tools21k project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = 'django-insecure-fcj6*kdqc9zlf_n+wbqowdwredzf(yh*!nq7s%e^t^^pi-qb3p'
DEBUG = False
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    
    # Third-party apps
    'ckeditor',
    'ckeditor_uploader',
    
    # Custom apps
    'main',
    'textutils',
  #  'fileconverter',
    'image_resizer',
    'videodownloader',
    'pdftools',
    'shortener',
    #'qrscanner',
    'blog',  # Blog app
    'qrtools'
]
import cloudinary
import cloudinary.uploader
import cloudinary.api
from dotenv import load_dotenv
import os

load_dotenv()

# CLOUDINARY CONFIGURATION - HARDCODED FOR TESTING
cloudinary.config(
    cloud_name='dknrvzf7i',
    api_key='644493262717686',
    api_secret='DntsCMw1SglDAwGAguX8iKhZzJ0',  # Copy full secret from your screenshot
    secure=True
)
SITE_ID = 1
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tools21k.urls'
QR_RATE_LIMIT_REQUESTS = 20  # requests per window
QR_RATE_LIMIT_WINDOW = 60  # seconds
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'tools21k.wsgi.application'



import dj_database_url

#DATABASES = {
   # 'default': dj_database_url.parse(
      #  'postgresql://neondb_owner:npg_1FUvlDPnITc4@ep-rough-hat-aduig6om-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require',
     #   conn_max_age=600,
  #      ssl_require=True
 #   )
#}
# ============================================
# DATABASE CONFIGURATION - SQLite (Temporary)
# ============================================

# Try Neon PostgreSQL first, fallback to SQLite
def get_database_config():
    """
    Attempts to connect to Neon PostgreSQL.
    Falls back to SQLite if connection fails or times out.
    """
    
    # Neon Database URL
    NEON_DATABASE_URL = 'postgresql://neondb_owner:npg_1FUvlDPnITc4@ep-rough-hat-aduig6om-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require'
    
    # Check if we should use SQLite (via environment variable)
    USE_SQLITE = os.environ.get('USE_SQLITE', 'False').lower() == 'true'
    
    if USE_SQLITE:
        print("⚠️  Using SQLite (forced by USE_SQLITE environment variable)")
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
    
    try:
        # Test Neon connection with short timeout
        import psycopg2
        
        print("🔍 Testing Neon PostgreSQL connection...")
        
        # Quick connection test (5 second timeout)
        conn = psycopg2.connect(
            NEON_DATABASE_URL,
            connect_timeout=5
        )
        conn.close()
        
        print("✅ Neon PostgreSQL connected successfully!")
        
        # Return Neon configuration with optimized settings
        return {
            'default': dj_database_url.parse(
                NEON_DATABASE_URL,
                conn_max_age=300,  # Reduced from 600 to 5 minutes
                conn_health_checks=True,  # Enable connection health checks
                ssl_require=True
            )
        }
        
    except ImportError:
        print("⚠️  psycopg2 not installed. Installing: pip install psycopg2-binary")
        print("⚠️  Falling back to SQLite...")
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
        
    except Exception as e:
        print(f"❌ Neon PostgreSQL connection failed: {str(e)}")
        print("⚠️  Automatically falling back to SQLite...")
        return {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Set database configuration
DATABASES = get_database_config()

# Additional database optimization for Neon
if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    # Add these options to handle Neon's connection limits
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 10,
        'options': '-c statement_timeout=30000',  # 30 second query timeout
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 5,
    }
    
    # Disable persistent connections in development to avoid timeout issues
    if DEBUG:
        DATABASES['default']['CONN_MAX_AGE'] = 0
        print("🔧 Development mode: Disabled persistent connections")

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Create necessary directories if not exists
os.makedirs(os.path.join(MEDIA_ROOT, 'downloads'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'blog_thumbnails'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'uploads'), exist_ok=True)

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['Format', 'Styles'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'],
            ['Source'],
            ['Maximize'],
        ],
        'height': 400,
        'width': '100%',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'extraPlugins': ','.join([
            'uploadimage',
            'image2',
            'uploadwidget',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
        ]),
        'removePlugins': 'image',
        'image2_alignClasses': ['image-left', 'image-center', 'image-right'],
        'image2_captionedClass': 'image-captioned',
        
        # CRITICAL: Disable content filtering to preserve custom HTML/CSS
        'allowedContent': True,
        'extraAllowedContent': '*(*){*}[*]',  # Allow all tags, classes, styles, and attributes
        'fillEmptyBlocks': False,
        'forcePasteAsPlainText': False,
        'enterMode': 2,  # CKEDITOR.ENTER_BR
        'fullPage': True,  # Allow full HTML page editing
    },
}


# Authentication Configuration
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'blog_list'

# Video Downloader Config
VIDEODOWNLOADER_CONFIG = {
    'MAX_FILE_SIZE': 1024 * 1024 * 500,  # 500MB
    'ALLOWED_PLATFORMS': ['youtube', 'instagram', 'tiktok', 'facebook'],
    'DEFAULT_QUALITY': 'best',
    'DOWNLOAD_TIMEOUT': 30,  # seconds
    'MAX_RETRIES': 3,
    'STORAGE_PATH': os.path.join(MEDIA_ROOT, 'downloads'),
    'THUMBNAIL_SIZE': (320, 180),
    'ENABLE_PROXY': True,
    'CONCURRENT_DOWNLOADS': 3,
}

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': 3600,  # 1 hour
    }
}
os.makedirs(os.path.join(MEDIA_ROOT, 'downloads'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'blog_thumbnails'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'uploads'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'author_profiles'), exist_ok=True)

# Default primary key field type

# For custom domain email (if using cPanel/hosting)
# Email Configuration for 21K Tools
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email.21k.tools'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'contact@21k.tools'
EMAIL_HOST_PASSWORD = '@nithish21KBC'
DEFAULT_FROM_EMAIL = '21K Tools <contact@21k.tools>'
SERVER_EMAIL = 'contact@21k.tools'
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'your-email@gmail.com'
#EMAIL_HOST_PASSWORD = 'your-app-password'  # NOT your regular password
DEFAULT_FROM_EMAIL = 'your-email@gmail.com'
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours
# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
# In settings.py
